### ISSUE TITLE
Fund, Campaign and Appeal ids not present in Blackbaud API endpoints

### ISSUE THREAD

**Issue by ephemerolfc** [blackbaud/powerbi-connector#6]
Hi 

First of all thanks for adding this officially on behalf of Blackbaud. I set this up a while ago using Grant Quick's original code so your version may be different, but he's not supporting that anymore.

I'm trying to report on gift summaries in Power BI dashboards, but it seems that the API endpoint for Gifts doesn't have anything to connect the gift data to the tables for Campaign, Fund or Appeal. Is that correct or am I missing something?

Thanks

Mark

**Comment by jrmaier** [comment]
I am not seeing any fields to create a relation between the tables.

**Comment by ephemerolfc** [comment]
To respond to my own Issue in case anyone else is looking for this, the tables for Campaign, Fund and Appeal (and a number of others) are not visible on the top level in Power BI but can be found by drilling down using Power Query.
